const codes={0:['Clear sky','☀️'],1:['Mainly clear','🌤️'],2:['Partly cloudy','⛅'],3:['Overcast','☁️'],45:['Fog','🌫️'],48:['Rime fog','🌫️'],51:['Light drizzle','🌦️'],53:['Drizzle','🌦️'],55:['Dense drizzle','🌧️'],61:['Light rain','🌧️'],63:['Rain','🌧️'],65:['Heavy rain','🌧️'],71:['Light snow','🌨️'],73:['Snow','🌨️'],75:['Heavy snow','❄️'],80:['Rain showers','🌦️'],81:['Moderate rain showers','🌧️'],82:['Heavy rain showers','⛈️'],95:['Thunderstorm','⛈️'],96:['Thunderstorm with hail','⛈️'],99:['Thunderstorm with hail','⛈️']};
const $=s=>document.querySelector(s), fmt=n=>new Intl.NumberFormat('en-US',{maximumFractionDigits:2}).format(n);
function clock(){const now=new Date(); $('#today').textContent=new Intl.DateTimeFormat('en-US',{weekday:'long',year:'numeric',month:'long',day:'numeric'}).format(now); document.querySelectorAll('.clock[data-zone]').forEach(clock=>{const zone=clock.dataset.zone, parts=Object.fromEntries(new Intl.DateTimeFormat('en-US',{timeZone:zone,hour:'numeric',minute:'numeric',hourCycle:'h23'}).formatToParts(now).filter(p=>p.type!=='literal').map(p=>[p.type,Number(p.value)])), hour=parts.hour%12, minute=parts.minute; clock.querySelector('.hour-hand').style.setProperty('--angle',(hour*30+minute*.5)+'deg'); clock.querySelector('.minute-hand').style.setProperty('--angle',(minute*6)+'deg'); clock.querySelector('.time').textContent=new Intl.DateTimeFormat('en-US',{timeZone:zone,hour:'2-digit',minute:'2-digit',hour12:false}).format(now);});} clock(); setInterval(clock,60000);
async function loadWeather(place){
  try {
    const g=await fetch('https://geocoding-api.open-meteo.com/v1/search?name='+encodeURIComponent(place)+'&count=1&language=en&format=json').then(r=>r.json());
    if(!g.results?.[0]) throw Error();
    const p=g.results[0], u='https://api.open-meteo.com/v1/forecast?latitude='+p.latitude+'&longitude='+p.longitude+'&current=temperature_2m,apparent_temperature,weather_code,wind_speed_10m&daily=weather_code,temperature_2m_max,precipitation_probability_max&timezone=auto&forecast_days=6';
    const d=await fetch(u).then(r=>r.json()), c=d.current, w=codes[c.weather_code]||['Weather unavailable','🌡️'];
    $('#place').textContent=p.name+(p.country?' · '+p.country:'');
    $('#temp').textContent=Math.round(c.temperature_2m)+'°';
    $('#condition').textContent=w[0]; $('#weather-icon').textContent=w[1];
    $('#apparent').textContent=Math.round(c.apparent_temperature)+'°';
    $('#rain').textContent=d.daily.precipitation_probability_max[0]+'%';
    $('#wind').textContent=Math.round(c.wind_speed_10m)+' km/h';
    $('#forecast').innerHTML=d.daily.time.slice(1).map((date,index)=>{
      const i=index+1, z=codes[d.daily.weather_code[i]]||['','🌡️'];
      return '<div class="day">'+new Intl.DateTimeFormat('en-US',{weekday:'short',timeZone:d.timezone}).format(new Date(date+'T12:00:00'))+'<span>'+z[1]+'</span><b>'+Math.round(d.daily.temperature_2m_max[i])+'°</b></div>';
    }).join('');
    localStorage.dashboardPlace=place;
  } catch { $('#condition').textContent='Unable to load weather data'; }
}
async function loadRates(){try { const d=await fetch('https://api.frankfurter.dev/v1/latest?base=EUR&symbols=USD,KRW').then(r=>r.json()), eur=d.rates.KRW, usd=eur/d.rates.USD; $('#usd-rate').textContent='₩'+fmt(usd); $('#eur-rate').textContent='₩'+fmt(eur); $('#rate-updated').textContent='As of '+d.date+' · ECB reference rates'; }catch{$('#rate-updated').textContent='Unable to load exchange rates';}}
function formatDate(date){return date.toISOString().slice(0,10);}
function drawRateChart(values){
  const chart=$('#rate-chart'), width=480, height=154, pad={top:12,right:8,bottom:24,left:42}, all=values.flatMap(item=>[item.usd,item.eur]), min=Math.min(...all), max=Math.max(...all), range=max-min||1, x=index=>pad.left+index*(width-pad.left-pad.right)/(values.length-1), y=value=>pad.top+(max-value)*(height-pad.top-pad.bottom)/range, path=key=>values.map((item,index)=>(index?'L':'M')+x(index).toFixed(1)+' '+y(item[key]).toFixed(1)).join(' '), label=value=>'₩'+Math.round(value).toLocaleString('en-US'), first=values[0], last=values.at(-1);
  chart.innerHTML='<svg viewBox="0 0 '+width+' '+height+'" role="img" aria-label="USD and EUR exchange rates against KRW over the last 30 days"><line class="gridline" x1="'+pad.left+'" x2="'+(width-pad.right)+'" y1="'+y(max)+'" y2="'+y(max)+'"/><line class="gridline" x1="'+pad.left+'" x2="'+(width-pad.right)+'" y1="'+y(min)+'" y2="'+y(min)+'"/><text x="0" y="'+(y(max)+4)+'">'+label(max)+'</text><text x="0" y="'+(y(min)+4)+'">'+label(min)+'</text><path class="usd-line" d="'+path('usd')+'"/><path class="eur-line" d="'+path('eur')+'"/><line class="hover-guide" x1="0" x2="0" y1="'+pad.top+'" y2="'+(height-pad.bottom)+'" visibility="hidden"/><circle class="usd-dot" r="4" fill="var(--mint)" visibility="hidden"/><circle class="eur-dot" r="4" fill="var(--accent)" visibility="hidden"/><text x="'+pad.left+'" y="'+(height-4)+'">'+first.date.slice(5)+'</text><text text-anchor="end" x="'+(width-pad.right)+'" y="'+(height-4)+'">'+last.date.slice(5)+'</text></svg><div class="rate-tooltip"></div>';
  const svg=chart.querySelector('svg'), tooltip=chart.querySelector('.rate-tooltip'), guide=svg.querySelector('.hover-guide'), usdDot=svg.querySelector('.usd-dot'), eurDot=svg.querySelector('.eur-dot');
  svg.addEventListener('pointermove',event=>{const bounds=svg.getBoundingClientRect(), point=(event.clientX-bounds.left)/bounds.width*width, index=Math.max(0,Math.min(values.length-1,Math.round((point-pad.left)/(width-pad.left-pad.right)*(values.length-1)))), item=values[index], cx=x(index); guide.setAttribute('x1',cx); guide.setAttribute('x2',cx); guide.setAttribute('visibility','visible'); [[usdDot,item.usd],[eurDot,item.eur]].forEach(([dot,value])=>{dot.setAttribute('cx',cx); dot.setAttribute('cy',y(value)); dot.setAttribute('visibility','visible');}); tooltip.innerHTML='<span>'+item.date+'</span><br><b>USD/KRW '+label(item.usd)+'</b><br><span class="eur">EUR/KRW '+label(item.eur)+'</span>'; tooltip.style.display='block'; tooltip.style.left=Math.min(bounds.width-140,Math.max(0,event.clientX-bounds.left+10))+'px'; tooltip.style.top='8px';});
  svg.addEventListener('pointerleave',()=>{guide.setAttribute('visibility','hidden'); usdDot.setAttribute('visibility','hidden'); eurDot.setAttribute('visibility','hidden'); tooltip.style.display='none';});
}
async function loadRateHistory(){try {const end=new Date(), start=new Date(end); start.setDate(end.getDate()-42); const d=await fetch('https://api.frankfurter.dev/v1/'+formatDate(start)+'..'+formatDate(end)+'?from=EUR&to=USD,KRW').then(r=>r.json()), values=Object.entries(d.rates).map(([date,rates])=>({date,eur:rates.KRW,usd:rates.KRW/rates.USD})).filter(item=>Number.isFinite(item.eur)&&Number.isFinite(item.usd)).slice(-30); if(values.length<2) throw Error(); drawRateChart(values);}catch{$('#rate-chart').textContent='Unable to load chart data';}}
const timeFactors={s:1,ms:1e-3,us:1e-6,ns:1e-9}, timeFormat=new Intl.NumberFormat('en-US',{maximumSignificantDigits:10});
function updateTime(){const value=Number($('#time-input').value), seconds=value*timeFactors[$('#time-unit').value]; ['s','ms','us','ns'].forEach(unit=>$('#time-'+unit).textContent=Number.isFinite(seconds)?timeFormat.format(seconds/timeFactors[unit]):'—');}
function updateBase(){const input=$('#base-input').value.trim(), unit=$('#base-unit').value, note=$('#base-note'), patterns={bin:/^[01]+$/,dec:/^\d+$/,hex:/^[\da-f]+$/i}, clean=input.replace(/^0[bBxX]/,''); try {if(!clean||!patterns[unit].test(clean)) throw Error(); const value=BigInt(unit==='bin'?'0b'+clean:unit==='hex'?'0x'+clean:clean), binary=value.toString(2).replace(/\B(?=(?:\d{4})+(?!\d))/g,' '); $('#base-bin').textContent=binary; $('#base-dec').textContent=value.toLocaleString('en-US'); $('#base-hex').textContent=value.toString(16).toUpperCase(); note.textContent='Supports arbitrary-size integer conversion.'; note.className='converter-note';}catch{['bin','dec','hex'].forEach(unit=>$('#base-'+unit).textContent='—'); note.textContent='Enter a positive integer valid for the selected base.'; note.className='converter-note error';}}
$('#time-input').addEventListener('input',updateTime); $('#time-unit').addEventListener('change',updateTime); $('#base-input').addEventListener('input',updateBase); $('#base-unit').addEventListener('change',updateBase); updateTime(); updateBase();
const dialog=$('#place-dialog'); $('#change-place').onclick=()=>dialog.showModal(); $('#save-place').onclick=e=>{e.preventDefault(); const value=$('#place-input').value.trim(); if(value){loadWeather(value); dialog.close();}}; const savedPlace=localStorage.dashboardPlace, initialPlace=!savedPlace||savedPlace==='Seoul'?'Vienna':savedPlace; loadWeather(initialPlace); loadRates(); loadRateHistory();
const stockSymbolsKey='dashboardStockSymbols', stockCapacityKey='dashboardStockCapacity', stocksVisibleKey='dashboardStocksVisible', defaultSymbols=['NASDAQ:TSLA','NASDAQ:SNDK','NASDAQ:SKHY'];
let stockSymbols=[...defaultSymbols], stockCapacity=3;
try {const saved=JSON.parse(localStorage.getItem(stockSymbolsKey)); if(Array.isArray(saved)&&saved.length>=1) stockSymbols=saved.slice(0,10).map(symbol=>typeof symbol==='string'?symbol:'');} catch {}
stockCapacity=Math.max(1,Math.min(10,Number(localStorage.getItem(stockCapacityKey))||stockSymbols.length)); while(stockSymbols.length<stockCapacity) stockSymbols.push('');
function renderStocks(){const list=$('#stock-list'); list.replaceChildren(...stockSymbols.filter(Boolean).map(symbol=>{const row=document.createElement('div'), ticker=document.createElement('tv-single-ticker'); row.className='stock-widget'; ticker.setAttribute('symbol',symbol); ticker.setAttribute('theme','dark'); ticker.setAttribute('transparent',''); ticker.setAttribute('locale','en'); row.append(ticker); return row;})); refreshWatchlist();}
function refreshWatchlist(){document.querySelectorAll('.stock-widget tv-single-ticker').forEach(ticker=>ticker.replaceWith(ticker.cloneNode(true))); $('#stock-updated').textContent='TradingView quotes · Refreshed '+new Intl.DateTimeFormat('en-US',{hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date())+' · Market data may be delayed';}
function setStocksVisible(visible){$('#stocks-card').hidden=!visible; $('#show-stocks').hidden=visible; localStorage.setItem(stocksVisibleKey,String(visible));}
function buildTickerSlots(capacity){const slots=$('#ticker-slots'); slots.replaceChildren(...Array.from({length:capacity},(_,index)=>{const row=document.createElement('div'), label=document.createElement('label'), input=document.createElement('input'); row.className='ticker-slot'; label.textContent='Ticker '+(index+1); input.type='text'; input.dataset.index=index; input.value=stockSymbols[index]||''; input.placeholder='e.g. NASDAQ:NVDA'; input.autocomplete='off'; row.append(label,input); return row;}));}
$('#manage-tickers').addEventListener('click',()=>{const dialog=$('#ticker-dialog'); $('#ticker-capacity').value=stockCapacity; $('#ticker-dialog-error').hidden=true; buildTickerSlots(stockCapacity); dialog.showModal();});
$('#ticker-capacity').addEventListener('input',event=>{if(event.target.value==='') return; const parsed=Math.trunc(Number(event.target.value)); if(!Number.isFinite(parsed)) return; const capacity=Math.max(1,Math.min(10,parsed)); event.target.value=capacity; buildTickerSlots(capacity);});
$('#ticker-capacity').addEventListener('change',event=>{const capacity=Math.max(1,Math.min(10,Math.trunc(Number(event.target.value))||1)); event.target.value=capacity; buildTickerSlots(capacity);});
$('#ticker-form').addEventListener('submit',event=>{event.preventDefault(); const capacity=Math.max(1,Math.min(10,Math.trunc(Number($('#ticker-capacity').value))||1)), symbols=[...document.querySelectorAll('#ticker-slots input')].map(input=>input.value.trim().toUpperCase()), invalid=symbols.find(symbol=>symbol&&!/^[A-Z0-9._-]+:[A-Z0-9._-]+$/.test(symbol)), error=$('#ticker-dialog-error'); if(invalid){error.textContent='Use EXCHANGE:TICKER, for example NASDAQ:NVDA.'; error.hidden=false; return;} stockCapacity=capacity; stockSymbols=symbols; localStorage.setItem(stockSymbolsKey,JSON.stringify(stockSymbols)); localStorage.setItem(stockCapacityKey,String(stockCapacity)); renderStocks(); $('#ticker-dialog').close();});
$('#cancel-tickers').addEventListener('click',()=>$('#ticker-dialog').close());
$('#hide-stocks').addEventListener('click',()=>setStocksVisible(false)); $('#show-stocks').addEventListener('click',()=>setStocksVisible(true)); if(localStorage.getItem(stocksVisibleKey)==='false') setStocksVisible(false);
renderStocks(); setInterval(refreshWatchlist,60000);
